
- hosts: localhost

  gather_facts: no
  vars:
    acc_inconsistency: []
  vars_prompt:
    - name: username
      prompt: "username"
      private: no
    - name: password
      prompt: "password"
    - name: valid
      promt: is valid (yes/no)
      private: no
  tasks:

  - name: run show version on remote devices
    exos_command:
      commands: show version
    register: ssh_1
    ignore_errors: yes

  - name: "Check admin access was ok"
    set_fact:
      acc_inconsistency: "{{ acc_inconsistency + [ inventory_hostname + ': admin access via SSH NOT ok!' ] }}"
    when: "(ssh_1.failed and valid | bool) or (not ssh_1.failed and not valid | bool)"

  - name: Analyze and print result
    debug:
       msg: "{{ 'Accounts ok' if (acc_inconsistency | length) == 0 else acc_inconsistency}}"
